version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ai_hr_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ai_hr_password}
      POSTGRES_DB: ${POSTGRES_DB:-ai_hr_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_hr_network
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    container_name: redis_db
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_hr_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:


networks:
  ai_hr_network:
    driver: bridge
